"""Add preferred layout in the scene

Revision ID: 13c18ea3e84f
Revises: drop_audio_base64
Create Date: 2026-03-05 18:29:30.239087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c18ea3e84f'
down_revision: Union[str, None] = 'drop_audio_base64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('custom_voices_user_id_fkey'), 'custom_voices', type_='foreignkey')
    op.create_foreign_key(None, 'custom_voices', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_prebuilt_voices_voice_id'), 'prebuilt_voices', type_='unique')
    op.drop_constraint(op.f('saved_voices_user_id_fkey'), 'saved_voices', type_='foreignkey')
    op.drop_constraint(op.f('fk_saved_voices_custom_voice_id'), 'saved_voices', type_='foreignkey')
    op.create_foreign_key(None, 'saved_voices', 'custom_voices', ['custom_voice_id'], ['id'])
    op.create_foreign_key(None, 'saved_voices', 'users', ['user_id'], ['id'])
    op.add_column('scenes', sa.Column('preferred_layout', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'preferred_layout')
    op.drop_constraint(None, 'saved_voices', type_='foreignkey')
    op.drop_constraint(None, 'saved_voices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_saved_voices_custom_voice_id'), 'saved_voices', 'custom_voices', ['custom_voice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('saved_voices_user_id_fkey'), 'saved_voices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_prebuilt_voices_voice_id'), 'prebuilt_voices', ['voice_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'custom_voices', type_='foreignkey')
    op.create_foreign_key(op.f('custom_voices_user_id_fkey'), 'custom_voices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
