"""baseline

Revision ID: 57640a829335
Revises: 
Create Date: 2026-02-28 16:58:25.774923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57640a829335'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_interval', sa.Enum('ONE_TIME', 'MONTHLY', 'ANNUAL', name='billinginterval'), nullable=False),
    sa.Column('video_limit', sa.Integer(), nullable=False),
    sa.Column('includes_studio', sa.Boolean(), nullable=False),
    sa.Column('includes_chat_editor', sa.Boolean(), nullable=False),
    sa.Column('includes_priority_support', sa.Boolean(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=2048), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', name='plantier'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('videos_used_this_period', sa.Integer(), nullable=False),
    sa.Column('video_limit_bonus', sa.Integer(), server_default='0', nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('custom_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('supported_video_style', sa.String(length=30), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('preview_image_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_templates_user_id'), 'custom_templates', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('blog_url', sa.String(length=2048), nullable=True),
    sa.Column('blog_content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SCRAPED', 'SCRIPTED', 'GENERATED', 'RENDERING', 'DONE', 'ERROR', name='projectstatus'), nullable=False),
    sa.Column('voice_gender', sa.String(length=10), nullable=False),
    sa.Column('voice_accent', sa.String(length=10), nullable=False),
    sa.Column('accent_color', sa.String(length=20), nullable=False),
    sa.Column('bg_color', sa.String(length=20), nullable=False),
    sa.Column('text_color', sa.String(length=20), nullable=False),
    sa.Column('animation_instructions', sa.Text(), nullable=True),
    sa.Column('studio_unlocked', sa.Boolean(), nullable=False),
    sa.Column('studio_port', sa.Integer(), nullable=True),
    sa.Column('player_port', sa.Integer(), nullable=True),
    sa.Column('r2_video_key', sa.String(length=512), nullable=True),
    sa.Column('r2_video_url', sa.String(length=2048), nullable=True),
    sa.Column('logo_r2_key', sa.String(length=512), nullable=True),
    sa.Column('logo_r2_url', sa.String(length=2048), nullable=True),
    sa.Column('logo_position', sa.String(length=20), nullable=False),
    sa.Column('logo_opacity', sa.Float(), nullable=False),
    sa.Column('logo_size', sa.Float(), nullable=False),
    sa.Column('custom_voice_id', sa.String(length=100), nullable=True),
    sa.Column('template', sa.String(length=50), nullable=False),
    sa.Column('video_style', sa.String(length=30), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('ai_assisted_editing_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'AUDIO', name='assettype'), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('r2_key', sa.String(length=512), nullable=True),
    sa.Column('r2_url', sa.String(length=2048), nullable=True),
    sa.Column('excluded', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=False),
    sa.Column('remotion_code', sa.Text(), nullable=True),
    sa.Column('voiceover_path', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED', 'COMPLETED', 'REQUIRES_ACTION', name='subscriptionstatus'), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('videos_used', sa.Integer(), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_project_id'), 'subscriptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_project_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('scenes')
    op.drop_table('chat_messages')
    op.drop_table('assets')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_custom_templates_user_id'), table_name='custom_templates')
    op.drop_table('custom_templates')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###