"""add cascade delete to edit history

Revision ID: 7326b571b0a6
Revises: dd4f20e21341
Create Date: 2026-03-03 15:08:24.423247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7326b571b0a6'
down_revision: Union[str, None] = 'dd4f20e21341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_edit_history_project_id_fkey'), 'project_edit_history', type_='foreignkey')
    op.create_foreign_key(None, 'project_edit_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('scene_edit_history_project_id_fkey'), 'scene_edit_history', type_='foreignkey')
    op.drop_constraint(op.f('scene_edit_history_scene_id_fkey'), 'scene_edit_history', type_='foreignkey')
    op.create_foreign_key(None, 'scene_edit_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scene_edit_history', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scene_edit_history', type_='foreignkey')
    op.drop_constraint(None, 'scene_edit_history', type_='foreignkey')
    op.create_foreign_key(op.f('scene_edit_history_scene_id_fkey'), 'scene_edit_history', 'scenes', ['scene_id'], ['id'])
    op.create_foreign_key(op.f('scene_edit_history_project_id_fkey'), 'scene_edit_history', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_edit_history', type_='foreignkey')
    op.create_foreign_key(op.f('project_edit_history_project_id_fkey'), 'project_edit_history', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
