"""add project font family

Revision ID: 7ed594338d45
Revises: 13c18ea3e84f
Create Date: 2026-03-11 17:58:25.368983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed594338d45'
down_revision: Union[str, None] = '13c18ea3e84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('font_family', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'font_family')
    # ### end Alembic commands ###
