"""edit history tracking

Revision ID: dd4f20e21341
Revises: add_standard_plan
Create Date: 2026-03-02 20:21:46.045754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4f20e21341'
down_revision: Union[str, None] = 'add_standard_plan'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('is_ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_edit_history_edited_at'), 'project_edit_history', ['edited_at'], unique=False)
    op.create_index(op.f('ix_project_edit_history_project_id'), 'project_edit_history', ['project_id'], unique=False)
    op.create_index('ix_project_edit_project', 'project_edit_history', ['project_id'], unique=False)
    op.create_table('scene_edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_instruction', sa.Text(), nullable=True),
    sa.Column('is_ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_edit_history_edited_at'), 'scene_edit_history', ['edited_at'], unique=False)
    op.create_index(op.f('ix_scene_edit_history_project_id'), 'scene_edit_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_scene_edit_history_scene_id'), 'scene_edit_history', ['scene_id'], unique=False)
    op.create_index('ix_scene_edit_project_scene', 'scene_edit_history', ['project_id', 'scene_id'], unique=False)
    op.alter_column('projects', 'logo_size',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('projects', 'video_style',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("'explainer'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'video_style',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'explainer'::character varying"))
    op.alter_column('projects', 'logo_size',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.drop_index('ix_scene_edit_project_scene', table_name='scene_edit_history')
    op.drop_index(op.f('ix_scene_edit_history_scene_id'), table_name='scene_edit_history')
    op.drop_index(op.f('ix_scene_edit_history_project_id'), table_name='scene_edit_history')
    op.drop_index(op.f('ix_scene_edit_history_edited_at'), table_name='scene_edit_history')
    op.drop_table('scene_edit_history')
    op.drop_index('ix_project_edit_project', table_name='project_edit_history')
    op.drop_index(op.f('ix_project_edit_history_project_id'), table_name='project_edit_history')
    op.drop_index(op.f('ix_project_edit_history_edited_at'), table_name='project_edit_history')
    op.drop_table('project_edit_history')
    # ### end Alembic commands ###
