import PublicHeader from "../components/public/PublicHeader";
import PublicFooter from "../components/public/PublicFooter";
import Seo from "../components/seo/Seo";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-gray-900">
      <Seo
        title="Terms of Service"
        description="Read the Terms of Service for Blog2Video, the blog-to-video workflow platform by FireBird Technologies."
        path="/terms"
      />
      <PublicHeader />

      <div className="max-w-3xl mx-auto px-6 py-16">
        <header className="mb-10">
          <h1 className="text-3xl font-semibold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500">Last updated: May 11, 2025</p>
        </header>

        <div className="prose prose-gray max-w-none space-y-8 text-sm text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Agreement to Terms</h2>
            <p>
              By accessing or using Blog2Video at <a href="https://blog2video.app" className="text-purple-600 hover:underline">blog2video.app</a> ("the Service"), you agree to be bound by these Terms of Service ("Terms"). The Service is operated by FireBird Technologies ("we", "us", or "our"). If you do not agree to these Terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. Description of Service</h2>
            <p>
              Blog2Video is a SaaS platform that converts blog posts, articles, PDFs, and other written content into videos using AI-powered workflows. Features include video generation, template customization, and content distribution tools.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Accounts</h2>
            <p>
              You must create an account to access most features. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 18 years old to use the Service. You agree to provide accurate, current, and complete information during registration and to update such information as needed.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Subscriptions and Payment</h2>
            <p>
              Certain features of the Service require a paid subscription. By subscribing, you agree to pay the applicable fees as described on our Pricing page. Subscriptions renew automatically unless cancelled before the renewal date. You may cancel your subscription at any time through your account settings. Fees are non-refundable except where required by applicable law or as otherwise stated in our refund policy. We reserve the right to change pricing with reasonable notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. Your Content</h2>
            <p>
              You retain all ownership rights to the content you submit to the Service ("User Content"). By submitting User Content, you grant us a limited, non-exclusive, royalty-free license to process, store, and transform that content solely for the purpose of providing the Service to you.
            </p>
            <p className="mt-2">
              You represent and warrant that: (a) you own or have the necessary rights to the User Content you submit; (b) the User Content does not infringe any third-party intellectual property rights; and (c) the User Content complies with these Terms and all applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. AI-Generated Output</h2>
            <p>
              Videos and other outputs generated by the Service are derived from your User Content using AI models. You are solely responsible for reviewing AI-generated output before publication or distribution. We do not guarantee the accuracy, completeness, or fitness of AI-generated content for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Prohibited Uses</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Infringe any third-party intellectual property, privacy, or other rights</li>
              <li>Generate or distribute misleading, defamatory, or harmful content</li>
              <li>Attempt to reverse-engineer, scrape, or exploit the Service</li>
              <li>Violate any applicable law or regulation</li>
              <li>Transmit viruses, malware, or other harmful code</li>
              <li>Harass, abuse, or harm any person or entity</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Intellectual Property</h2>
            <p>
              The Service, including its design, code, trademarks, and all content we create, is owned by FireBird Technologies and protected by applicable intellectual property laws. Nothing in these Terms grants you any right to use our trademarks or branding without our prior written consent.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time for violation of these Terms or for any other reason at our discretion, with or without notice. You may terminate your account at any time by contacting us. Upon termination, your right to use the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Disclaimers</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">11. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, FIREBIRD TECHNOLOGIES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE. OUR AGGREGATE LIABILITY SHALL NOT EXCEED THE AMOUNTS PAID BY YOU TO US IN THE THREE MONTHS PRECEDING THE CLAIM.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">12. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material changes by updating the "Last updated" date above or by sending an email to your registered address. Your continued use of the Service after changes are posted constitutes your acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">13. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with applicable law. Any disputes shall be resolved in the competent courts of the jurisdiction in which FireBird Technologies operates.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">14. Contact</h2>
            <p>
              If you have questions about these Terms, please contact us at:{" "}
              <a
                href="mailto:arslan@firebird-technologies.com"
                className="text-purple-600 hover:underline"
              >
                arslan@firebird-technologies.com
              </a>
            </p>
          </section>

        </div>
      </div>

      <PublicFooter />
    </div>
  );
}
