import { createContext, useContext, useState, type FC } from "react";
import { posterUrl, type PosterOrientation } from "../templatePreviewRegistry";

/**
 * When `true`, wrapped previews always render live (the Remotion <Player> / CSS
 * preview) even in `thumbnailMode`. The poster capture route
 * ({@link ../../pages/CapturePage}) sets this so it can screenshot the real
 * rendered scene instead of an (as-yet-nonexistent) poster.
 */
export const CaptureContext = createContext(false);

/**
 * Wraps a built-in preview component so that in `thumbnailMode` it renders the
 * template's static poster (and never mounts the underlying preview — zero
 * Players), while the live preview renders when active. Used by the registry to
 * wrap every built-in landscape/portrait preview without editing each file.
 *
 * Why this exists
 * ───────────────
 * Every built-in preview's live render is expensive — the Player-based ones each
 * hold a full Remotion runtime + canvas contexts in memory even while paused, and
 * the carousel/step-2 grid mount many at once. On mobile that exhausts memory and
 * reloads/crashes the tab. Showing a flat `<img>` poster in `thumbnailMode` holds
 * zero Players; the live preview only renders when active (centered in the
 * carousel, in the fullscreen modal, or the step-2 "Selected Template").
 *
 * Posters are baked assets under `public/template-posters/`, regenerated by
 * `npm run posters:build`. If a poster is missing/broken the `onError` fallback
 * renders the live preview, so nothing ever shows blank. In capture context
 * ({@link CaptureContext} = true) the wrapped preview always renders live so the
 * capture route can screenshot it.
 */
export function withPoster(
  templateId: string,
  orientation: PosterOrientation,
  Preview: FC<{ thumbnailMode?: boolean }>,
): FC<{ thumbnailMode?: boolean }> {
  const Wrapped: FC<{ thumbnailMode?: boolean }> = ({ thumbnailMode = false }) => {
    const capturing = useContext(CaptureContext);
    const [failed, setFailed] = useState(false);
    if (thumbnailMode && !capturing && !failed) {
      const aspect = orientation === "portrait" ? "9 / 16" : "16 / 9";
      return (
        <div
          style={{
            width: "100%",
            height: "100%",
            overflow: "hidden",
            position: "relative",
            borderRadius: 12,
          }}
        >
          <img
            src={posterUrl(templateId, orientation)}
            alt=""
            loading="lazy"
            decoding="async"
            onError={() => setFailed(true)}
            style={{
              display: "block",
              width: "100%",
              height: "100%",
              objectFit: "cover",
              borderRadius: 12,
            }}
          />
        </div>
      );
    }
    return <Preview thumbnailMode={thumbnailMode} />;
  };
  Wrapped.displayName = `withPoster(${templateId},${orientation})`;
  return Wrapped;
}
