import React from "react";
import {
  AbsoluteFill,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import type { ChronicleLayoutProps } from "../types";
import { useFitText } from "../components/useFitText";
import {
  CHRONICLE_BODY_FONT,
  CHRONICLE_HEADING_FONT,
} from "../../../../fonts/chronicle-defaults";

/**
 * ChapterPlate — section-title card, redesigned as an **Illuminated Incipit**.
 *
 * Modeled on the opening page of a medieval illuminated manuscript (Book of
 * Kells / Lindisfarne Gospels):
 *   - Heavy painted outer gold frame with a vermillion + azure diamond strip
 *   - Four corner rosettes (gold discs with red/blue petals)
 *   - Inner gold-leaf panel with a sheen sweep and painted corner sprigs
 *   - Optional small-caps *kicker* (from `subtitle`) above the title
 *   - Title in red "rubric" ink with gold drop-shadow
 *   - Painted sprig divider below the title
 *   - Body paragraph (the scene's `narration` / "display text") in italic
 *     brown ink, centered, with its first letter slightly enlarged in
 *     vermillion as a whisper of an illuminated initial.
 *
 * - NO "Chapter", "Chapter N", or Roman numeral content.
 * - Strips any stray "Chapter N:" / "Ch. N:" prefix that may have been
 *   generated by the LLM for older videos, so old data looks clean too.
 */
export const ChapterPlate: React.FC<ChronicleLayoutProps> = ({
  title = "The Story Continues",
  narration,
  subtitle,
  accentColor = "#B8860B",
  textColor = "#2A1810",
  aspectRatio = "landscape",
  titleFontSize,
  descriptionFontSize,
  titleFontSizeIsUserSet,
  descriptionFontSizeIsUserSet,
  fontFamily,
}) => {
  const frame = useCurrentFrame();
  const { durationInFrames, height, width, fps } = useVideoConfig();
  const p = aspectRatio === "portrait" || height > width;

  // ── Defensive title cleanup — strip "Chapter N:", "Ch. N:", "Chapter I:",
  // "Chapter One:", etc. off the front of older LLM-generated titles.
  const cleanTitle = stripChapterPrefix(title);

  // ── Timing ─────────────────────────────────────────────
  const FRAME_PAINT_START = 0;
  const FRAME_PAINT_END = 24;
  const PANEL_IN_START = 16;
  const PANEL_IN_END = 34;
  const TITLE_IN_START = 30;
  const DIVIDER_IN = 52;
  const CAPTION_IN_START = 60;

  // Frame paints in (top → right → bottom → left)
  const framePaint = interpolate(
    frame,
    [FRAME_PAINT_START, FRAME_PAINT_END],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // Inner panel fades + scales up
  const panelSpring = spring({
    frame: frame - PANEL_IN_START,
    fps,
    config: { damping: 15, stiffness: 110, mass: 1 },
  });
  const panelOp = interpolate(
    frame,
    [PANEL_IN_START, PANEL_IN_END],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // Title reveals
  const titleOp = interpolate(
    frame,
    [TITLE_IN_START, TITLE_IN_START + 18],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );
  const titleRise = interpolate(
    frame,
    [TITLE_IN_START, TITLE_IN_START + 22],
    [20, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // Sprig divider paints in
  const dividerProgress = interpolate(
    frame,
    [DIVIDER_IN, DIVIDER_IN + 20],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // Caption fades in
  const captionOp = interpolate(
    frame,
    [CAPTION_IN_START, CAPTION_IN_START + 22],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // Outro fade
  const outroFade = interpolate(
    frame,
    [durationInFrames - 18, durationInFrames],
    [1, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

  // ── Geometry ────────────────────────────────────────────
  const pageW = p ? width * 0.84 : width * 0.72;
  const pageH = p ? height * 0.76 : height * 0.82;
  const frameInset = p ? 28 : 36; // thickness of the painted border band
  const cornerRosette = p ? 64 : 84;

  // ── Palette ─────────────────────────────────────────────
  const GOLD = accentColor;
  const GOLD_LIGHT = lightenHex(accentColor, 0.18);
  const GOLD_DEEP = darkenHex(accentColor, 0.22);
  const VERMILLION = "#9E2B1D"; // rubric red
  const AZURE = "#1F3C74"; // lapis blue
  const EMERALD = "#2F5D3A";
  const INK = textColor;
  const PARCH_BRIGHT = "#F7ECD0";

  const heading = fontFamily ?? CHRONICLE_HEADING_FONT;
  const body = fontFamily ?? CHRONICLE_BODY_FONT;

  // Narration is the *body* of the illuminated page. Subtitle (if given and
  // distinct from the title) becomes a small small-caps kicker above the title.
  const bodyText = (narration ?? "").trim();
  const rawSubtitle = (subtitle ?? "").trim();
  const kickerText =
    rawSubtitle &&
    rawSubtitle.toLowerCase() !== cleanTitle.toLowerCase() &&
    rawSubtitle.toLowerCase() !== title.trim().toLowerCase() &&
    rawSubtitle.toLowerCase() !== bodyText.toLowerCase()
      ? rawSubtitle
      : "";

  const kickerFontSize = Math.max(14, (descriptionFontSize ?? (p ? 22 : 20)) * 0.7);

  /* ── Auto-fit ──────────────────────────────────────────────
     Title and narration are unbounded user input in a fixed-size illuminated
     panel (overflow:hidden); long copy was clipped, and the title previously
     relied on a character-count guess (computeTitleFont) rather than real
     measurement. Measure the real available height and shrink to fit. An
     explicitly chosen size is honored exactly (minPx === targetPx no-ops the
     hook). */
  const fitTitleRef = React.useRef<HTMLDivElement>(null);
  const fitBodyRef = React.useRef<HTMLDivElement>(null);
  const fitTitleTarget = titleFontSize ?? (p ? pageW * 0.09 * 1.15 : pageW * 0.08 * 1.15);
  const fitBodyTarget = descriptionFontSize ?? (p ? 32 : 28);
  const { px: titleFont } = useFitText(
    fitTitleRef,
    fitTitleTarget,
    titleFontSizeIsUserSet ? fitTitleTarget : Math.round(fitTitleTarget * 0.35),
    [cleanTitle, fitTitleTarget, titleFontSizeIsUserSet, p, pageH],
    Math.round(pageH * (p ? 0.24 : 0.28)),
  );
  const { px: bodyFontSize } = useFitText(
    fitBodyRef,
    fitBodyTarget,
    descriptionFontSizeIsUserSet ? fitBodyTarget : Math.round(fitBodyTarget * 0.5),
    [bodyText, fitBodyTarget, descriptionFontSizeIsUserSet, titleFont, p, pageH],
    Math.round(pageH * (p ? 0.24 : 0.26)),
  );

  return (
    <AbsoluteFill
      style={{
        opacity: outroFade,
        alignItems: "center",
        justifyContent: "center",
        fontFamily: body,
      }}
    >
      {/* Outer illuminated page */}
      <div
        style={{
          position: "relative",
          width: pageW,
          height: pageH,
          transform: `scale(${0.96 + 0.04 * Math.min(1, framePaint * 1.2)})`,
          filter: "drop-shadow(0 28px 40px rgba(20,10,4,0.35))",
        }}
      >
        {/* ─────── Painted outer border (gold + diamond fresco) ─────── */}
        <div
          style={{
            position: "absolute",
            inset: 0,
            background: `
              linear-gradient(to right,
                rgba(0,0,0,0.2) 0%,
                rgba(255,220,150,0.15) 30%,
                rgba(0,0,0,0) 60%,
                rgba(255,220,150,0.1) 90%,
                rgba(0,0,0,0.2) 100%),
              linear-gradient(135deg, ${GOLD_LIGHT} 0%, ${GOLD} 35%, ${GOLD_DEEP} 100%)
            `,
            boxShadow: `
              inset 0 0 0 2px #3A2A08,
              inset 0 0 0 3px ${GOLD_DEEP},
              0 0 0 2px #3A2A08
            `,
            clipPath: paintedFrameMask(framePaint),
          }}
        />

        {/* Painted diamond pattern strip inside the gold frame */}
        <div
          style={{
            position: "absolute",
            top: frameInset * 0.45,
            left: frameInset * 0.45,
            right: frameInset * 0.45,
            bottom: frameInset * 0.45,
            pointerEvents: "none",
            opacity: framePaint,
          }}
        >
          {/* Top strip */}
          <FrescoStrip
            orientation="horizontal"
            length={pageW - frameInset * 0.9}
            thickness={frameInset * 0.8}
            style={{ top: 0, left: 0 }}
            vermillion={VERMILLION}
            azure={AZURE}
            emerald={EMERALD}
            gold={GOLD}
          />
          {/* Bottom strip */}
          <FrescoStrip
            orientation="horizontal"
            length={pageW - frameInset * 0.9}
            thickness={frameInset * 0.8}
            style={{ bottom: 0, left: 0 }}
            vermillion={VERMILLION}
            azure={AZURE}
            emerald={EMERALD}
            gold={GOLD}
          />
          {/* Left strip */}
          <FrescoStrip
            orientation="vertical"
            length={pageH - frameInset * 0.9}
            thickness={frameInset * 0.8}
            style={{ top: 0, left: 0 }}
            vermillion={VERMILLION}
            azure={AZURE}
            emerald={EMERALD}
            gold={GOLD}
          />
          {/* Right strip */}
          <FrescoStrip
            orientation="vertical"
            length={pageH - frameInset * 0.9}
            thickness={frameInset * 0.8}
            style={{ top: 0, right: 0 }}
            vermillion={VERMILLION}
            azure={AZURE}
            emerald={EMERALD}
            gold={GOLD}
          />
        </div>

        {/* ─────── Corner rosettes (decorative bosses) ─────── */}
        {[
          { top: -cornerRosette / 2.4, left: -cornerRosette / 2.4 },
          { top: -cornerRosette / 2.4, right: -cornerRosette / 2.4 },
          { bottom: -cornerRosette / 2.4, left: -cornerRosette / 2.4 },
          { bottom: -cornerRosette / 2.4, right: -cornerRosette / 2.4 },
        ].map((pos, i) => (
          <div
            key={`rosette-${i}`}
            style={{
              position: "absolute",
              width: cornerRosette,
              height: cornerRosette,
              opacity: Math.max(
                0,
                Math.min(1, framePaint * 1.4 - i * 0.08),
              ),
              transform: `scale(${Math.min(1, framePaint * 1.2)})`,
              ...pos,
              zIndex: 3,
            }}
          >
            <Rosette
              gold={GOLD}
              goldLight={GOLD_LIGHT}
              goldDeep={GOLD_DEEP}
              vermillion={VERMILLION}
              azure={AZURE}
            />
          </div>
        ))}

        {/* ─────── Inner panel (gold leaf + painted field for title) ─────── */}
        <div
          style={{
            position: "absolute",
            top: frameInset * 1.25,
            left: frameInset * 1.25,
            right: frameInset * 1.25,
            bottom: frameInset * 1.25,
            background: `
              radial-gradient(ellipse at 30% 20%, rgba(255,230,170,0.45) 0%, rgba(255,230,170,0) 55%),
              radial-gradient(ellipse at center, ${PARCH_BRIGHT} 0%, #EDDFB8 65%, #D9C488 100%)
            `,
            boxShadow: `
              inset 0 0 0 1px ${GOLD_DEEP},
              inset 0 0 0 3px #E9D097,
              inset 0 0 60px rgba(184,134,11,0.22),
              inset 0 0 140px rgba(50,25,10,0.15)
            `,
            opacity: panelOp,
            transform: `scale(${interpolate(panelSpring, [0, 1], [0.96, 1])})`,
            transformOrigin: "center center",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            padding: p ? "10% 8%" : "8% 10%",
            overflow: "hidden",
          }}
        >
          {/* Subtle gold-leaf shimmer sheen moving across the panel */}
          <div
            style={{
              position: "absolute",
              inset: 0,
              background: `linear-gradient(115deg,
                rgba(255,255,220,0) 35%,
                rgba(255,240,180,0.25) 50%,
                rgba(255,255,220,0) 65%
              )`,
              transform: `translateX(${interpolate(frame, [PANEL_IN_END, PANEL_IN_END + 60], [-200, 200], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })}%)`,
              mixBlendMode: "overlay",
              pointerEvents: "none",
            }}
          />

          {/* Small painted sprig decorations at the four inner corners */}
          {(
            [
              { corner: "tl", rot: 0 },
              { corner: "tr", rot: 90 },
              { corner: "br", rot: 180 },
              { corner: "bl", rot: 270 },
            ] as const
          ).map(({ corner, rot }) => {
            const gap = p ? 18 : 24;
            const pos: React.CSSProperties =
              corner === "tl"
                ? { top: gap, left: gap }
                : corner === "tr"
                  ? { top: gap, right: gap }
                  : corner === "br"
                    ? { bottom: gap, right: gap }
                    : { bottom: gap, left: gap };
            return (
              <div
                key={`sprig-${corner}`}
                style={{
                  position: "absolute",
                  width: p ? 52 : 62,
                  height: p ? 52 : 62,
                  transform: `rotate(${rot}deg)`,
                  opacity: panelOp * 0.85,
                  ...pos,
                }}
              >
                <PaintedSprig
                  gold={GOLD_DEEP}
                  vermillion={VERMILLION}
                  azure={AZURE}
                />
              </div>
            );
          })}

          {/* ─────── Optional kicker (small-caps super-title) ─────── */}
          {kickerText && (
            <div
              style={{
                fontFamily: body,
                fontSize: kickerFontSize,
                color: GOLD_DEEP,
                letterSpacing: "0.42em",
                textTransform: "uppercase",
                opacity: titleOp * 0.85,
                marginBottom: p ? 10 : 14,
                zIndex: 2,
              }}
            >
              {kickerText}
            </div>
          )}

          {/* ─────── Title (rubric red with gold shadow) ─────── */}
          <div
            ref={fitTitleRef}
            style={{
              fontFamily: heading,
              fontWeight: 900,
              fontSize: titleFont,
              lineHeight: 1.05,
              letterSpacing: "0.02em",
              textAlign: "center",
              color: VERMILLION,
              opacity: titleOp,
              transform: `translateY(${titleRise}px)`,
              textShadow: `
                2px 2px 0 ${GOLD},
                3px 3px 0 ${GOLD_DEEP},
                4px 4px 6px rgba(0,0,0,0.25)
              `,
              width: "100%",
              maxWidth: "92%",
              textTransform: "uppercase",
              zIndex: 2,
            }}
          >
            {cleanTitle}
          </div>

          {/* ─────── Painted sprig divider below title ─────── */}
          <div
            style={{
              marginTop: p ? 20 : 26,
              marginBottom: p ? 18 : 24,
              width: p ? "74%" : "56%",
              height: p ? 24 : 28,
              opacity: Math.max(0, dividerProgress),
              zIndex: 2,
            }}
          >
            <SprigDivider
              progress={dividerProgress}
              gold={GOLD}
              goldDeep={GOLD_DEEP}
              vermillion={VERMILLION}
            />
          </div>

          {/* ─────── Narration body — the "display text" of the scene ─────── */}
          {bodyText && (
            <div
              ref={fitBodyRef}
              style={{
                fontFamily: body,
                fontStyle: "italic",
                fontSize: bodyFontSize,
                color: INK,
                opacity: captionOp,
                textAlign: "center",
                lineHeight: 1.55,
                width: "100%",
                maxWidth: p ? "88%" : "78%",
                letterSpacing: "0.01em",
                zIndex: 2,
                textShadow: "0 1px 0 rgba(255,235,180,0.4)",
              }}
            >
              <span
                style={{
                  // First letter slightly enlarged — a whisper of a drop cap,
                  // in keeping with the manuscript aesthetic.
                  display: "inline",
                }}
              >
                <BodyWithFirstLetter text={bodyText} accent={VERMILLION} />
              </span>
            </div>
          )}
        </div>
      </div>
    </AbsoluteFill>
  );
};

// ══════════════════════════════════════════════════════════
// ── Helper components ─────────────────────────────────────
// ══════════════════════════════════════════════════════════

/**
 * Body paragraph with its first letter slightly enlarged and accented —
 * a subtle homage to the illuminated-initial tradition without shouting.
 */
const BodyWithFirstLetter: React.FC<{ text: string; accent: string }> = ({
  text,
  accent,
}) => {
  const trimmed = text.trim();
  if (!trimmed) return null;
  const first = trimmed.charAt(0);
  const rest = trimmed.slice(1);
  return (
    <>
      <span
        style={{
          fontStyle: "normal",
          fontWeight: 800,
          fontSize: "1.35em",
          color: accent,
          marginRight: "0.04em",
          letterSpacing: "0.01em",
        }}
      >
        {first}
      </span>
      {rest}
    </>
  );
};

/** A strip of medieval fresco — alternating vermillion, azure, gold diamonds. */
const FrescoStrip: React.FC<{
  orientation: "horizontal" | "vertical";
  length: number;
  thickness: number;
  style: React.CSSProperties;
  vermillion: string;
  azure: string;
  emerald: string;
  gold: string;
}> = ({ orientation, length, thickness, style, vermillion, azure, emerald, gold }) => {
  const horiz = orientation === "horizontal";
  const count = Math.max(4, Math.floor((horiz ? length : length) / (thickness * 1.2)));
  const colors = [vermillion, azure, gold, emerald];
  return (
    <div
      style={{
        position: "absolute",
        width: horiz ? length : thickness,
        height: horiz ? thickness : length,
        display: "flex",
        flexDirection: horiz ? "row" : "column",
        alignItems: "center",
        justifyContent: "center",
        gap: 2,
        overflow: "hidden",
        ...style,
      }}
    >
      {Array.from({ length: count }).map((_, i) => {
        const color = colors[i % colors.length];
        return (
          <svg
            key={i}
            viewBox="0 0 20 20"
            style={{
              width: thickness * 0.75,
              height: thickness * 0.75,
              flexShrink: 0,
            }}
          >
            {/* Diamond */}
            <path
              d="M10 1 L19 10 L10 19 L1 10 Z"
              fill={color}
              stroke="#2A1810"
              strokeWidth="0.8"
            />
            {/* Inner gold dot */}
            <circle cx="10" cy="10" r="2.4" fill={gold} stroke="#3A2A08" strokeWidth="0.5" />
          </svg>
        );
      })}
    </div>
  );
};

/** A painted corner rosette / boss. */
const Rosette: React.FC<{
  gold: string;
  goldLight: string;
  goldDeep: string;
  vermillion: string;
  azure: string;
}> = ({ gold, goldLight, goldDeep, vermillion, azure }) => (
  <svg viewBox="0 0 100 100" style={{ width: "100%", height: "100%" }}>
    <defs>
      <radialGradient id="ros-gold" cx="50%" cy="50%" r="55%">
        <stop offset="0%" stopColor={goldLight} />
        <stop offset="55%" stopColor={gold} />
        <stop offset="100%" stopColor={goldDeep} />
      </radialGradient>
    </defs>
    {/* Outer gold disc */}
    <circle cx="50" cy="50" r="48" fill="url(#ros-gold)" stroke="#3A2A08" strokeWidth="2" />
    {/* 8 petals */}
    {Array.from({ length: 8 }).map((_, i) => {
      const a = (i * 45 * Math.PI) / 180;
      const cx = 50 + Math.cos(a) * 24;
      const cy = 50 + Math.sin(a) * 24;
      return (
        <circle
          key={i}
          cx={cx}
          cy={cy}
          r="10"
          fill={i % 2 === 0 ? vermillion : azure}
          stroke="#1A0C04"
          strokeWidth="1"
        />
      );
    })}
    {/* Center boss */}
    <circle cx="50" cy="50" r="10" fill={goldDeep} stroke="#3A2A08" strokeWidth="1.5" />
    <circle cx="50" cy="50" r="4" fill={goldLight} />
  </svg>
);

/** A small painted sprig with vermillion berries and azure leaves. */
const PaintedSprig: React.FC<{
  gold: string;
  vermillion: string;
  azure: string;
}> = ({ gold, vermillion, azure }) => (
  <svg viewBox="0 0 100 100" style={{ width: "100%", height: "100%" }}>
    {/* Main stem */}
    <path
      d="M15 85 Q30 60 45 50 Q60 40 80 25"
      stroke={gold}
      strokeWidth="2.5"
      fill="none"
      strokeLinecap="round"
    />
    {/* Side stems */}
    <path d="M30 65 Q40 55 48 58" stroke={gold} strokeWidth="1.8" fill="none" strokeLinecap="round" />
    <path d="M55 45 Q65 38 70 40" stroke={gold} strokeWidth="1.8" fill="none" strokeLinecap="round" />
    {/* Leaves (azure) */}
    <ellipse cx="30" cy="60" rx="7" ry="4" fill={azure} transform="rotate(-30 30 60)" stroke="#0C1B38" strokeWidth="0.8" />
    <ellipse cx="58" cy="48" rx="6" ry="3.5" fill={azure} transform="rotate(-35 58 48)" stroke="#0C1B38" strokeWidth="0.8" />
    {/* Berries (vermillion) */}
    <circle cx="48" cy="58" r="3.5" fill={vermillion} stroke="#3A0B05" strokeWidth="0.8" />
    <circle cx="72" cy="38" r="3" fill={vermillion} stroke="#3A0B05" strokeWidth="0.8" />
    <circle cx="80" cy="25" r="2.6" fill={vermillion} stroke="#3A0B05" strokeWidth="0.8" />
  </svg>
);

/** Painted ornamental sprig divider that draws in from the center outward. */
const SprigDivider: React.FC<{
  progress: number;
  gold: string;
  goldDeep: string;
  vermillion: string;
}> = ({ progress, gold, goldDeep, vermillion }) => {
  const p = Math.max(0, Math.min(1, progress));
  return (
    <svg
      viewBox="0 0 600 50"
      style={{ width: "100%", height: "100%", overflow: "visible" }}
      preserveAspectRatio="none"
    >
      {/* Left branch */}
      <path
        d="M300 25 Q240 25 180 18 Q130 13 80 20 Q50 24 30 20"
        stroke={gold}
        strokeWidth="2.5"
        fill="none"
        strokeLinecap="round"
        strokeDasharray="500"
        strokeDashoffset={(1 - p) * 500}
      />
      {/* Right branch */}
      <path
        d="M300 25 Q360 25 420 32 Q470 37 520 30 Q550 26 570 30"
        stroke={gold}
        strokeWidth="2.5"
        fill="none"
        strokeLinecap="round"
        strokeDasharray="500"
        strokeDashoffset={(1 - p) * 500}
      />
      {/* Center fleur */}
      <g transform="translate(300 25)" opacity={Math.max(0, p * 1.4 - 0.3)}>
        <path
          d="M-18 0 L18 0 M0 -14 L0 14 M-10 -10 L10 10 M-10 10 L10 -10"
          stroke={goldDeep}
          strokeWidth="2"
          strokeLinecap="round"
        />
        <circle cx="0" cy="0" r="5" fill={vermillion} stroke="#3A0B05" strokeWidth="1" />
        <circle cx="0" cy="0" r="2" fill={gold} />
      </g>
      {/* Small berries on each branch */}
      {p > 0.4 && (
        <>
          <circle cx="80" cy="20" r="3" fill={vermillion} stroke="#3A0B05" strokeWidth="0.8" opacity={p} />
          <circle cx="180" cy="18" r="2.5" fill={vermillion} stroke="#3A0B05" strokeWidth="0.8" opacity={p} />
          <circle cx="420" cy="32" r="2.5" fill={vermillion} stroke="#3A0B05" strokeWidth="0.8" opacity={p} />
          <circle cx="520" cy="30" r="3" fill={vermillion} stroke="#3A0B05" strokeWidth="0.8" opacity={p} />
        </>
      )}
    </svg>
  );
};

// ══════════════════════════════════════════════════════════
// ── Utility functions ─────────────────────────────────────
// ══════════════════════════════════════════════════════════

/**
 * Strip "Chapter N:", "Chapter One:", "Ch. N:", Roman numerals like "I:",
 * etc. from the front of a title so old LLM-generated data renders clean.
 *
 *   "Chapter I: The Founding"      → "The Founding"
 *   "CHAPTER 1: The Everything…"    → "The Everything…"
 *   "Ch. 2 - A Reckoning"           → "A Reckoning"
 *   "II. The Reign"                 → "The Reign"
 *   "The Founding"                  → "The Founding"  (unchanged)
 */
export function stripChapterPrefix(raw: string): string {
  if (!raw) return raw;
  let t = raw.trim();

  // "Chapter N:", "Chapter One:", "Ch N:", "Ch. N:", optional "-" or ":" separator
  const chapterRe =
    /^\s*(?:chapter|ch\.?)\s+(?:\d+|[ivxlcdm]+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\s*[:\-–—.]?\s*/i;
  if (chapterRe.test(t)) {
    t = t.replace(chapterRe, "").trim();
  } else {
    // Standalone leading roman numeral + separator: "I:", "IV.", "XII —"
    const romanRe = /^\s*[IVXLCDM]{1,6}\s*[:\-–—.]\s*/;
    if (romanRe.test(t)) {
      t = t.replace(romanRe, "").trim();
    } else {
      // Leading bare arabic numeral: "1. The Founding", "2: Onward"
      const arabicRe = /^\s*\d{1,3}\s*[:\-–—.]\s*/;
      if (arabicRe.test(t)) {
        t = t.replace(arabicRe, "").trim();
      }
    }
  }

  // Catch "Being a Chronicle", "A Chronicle of …" style hardcoded-theme leftovers
  t = t.replace(/^\s*being\s+a\s+chronicle\b[:\-–—.,]?\s*/i, "").trim();

  return t || raw; // if stripping left nothing, use original
}

/**
 * Reveal the outer gold frame from top → right → bottom → left using a
 * polygon clip-path. At progress=0 it's invisible; at progress=1 it's full.
 */
function paintedFrameMask(progress: number): string {
  const p = Math.max(0, Math.min(1, progress));
  if (p <= 0) {
    return "polygon(0 0, 0 0, 0 0, 0 0)";
  }
  if (p >= 1) {
    return "polygon(0 0, 100% 0, 100% 100%, 0 100%)";
  }
  // Four-stage reveal: top (0-0.25), right (0.25-0.5), bottom (0.5-0.75), left (0.75-1)
  const topPct = Math.min(1, p / 0.25) * 100;
  const rightPct = Math.min(1, Math.max(0, (p - 0.25) / 0.25)) * 100;
  const bottomPct = Math.min(1, Math.max(0, (p - 0.5) / 0.25)) * 100;
  const leftPct = Math.min(1, Math.max(0, (p - 0.75) / 0.25)) * 100;
  return `polygon(
    0 0,
    ${topPct}% 0,
    ${topPct}% 0,
    100% 0,
    100% ${rightPct}%,
    100% ${rightPct}%,
    100% 100%,
    ${100 - bottomPct}% 100%,
    ${100 - bottomPct}% 100%,
    0 100%,
    0 ${100 - leftPct}%,
    0 ${100 - leftPct}%
  )`;
}

function darkenHex(hex: string, amt: number): string {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const num = parseInt(full, 16);
  let r = (num >> 16) - Math.round(255 * amt);
  let g = ((num >> 8) & 0xff) - Math.round(255 * amt);
  let b = (num & 0xff) - Math.round(255 * amt);
  r = Math.max(0, Math.min(255, r));
  g = Math.max(0, Math.min(255, g));
  b = Math.max(0, Math.min(255, b));
  return "#" + ((1 << 24) | (r << 16) | (g << 8) | b).toString(16).slice(1);
}

function lightenHex(hex: string, amt: number): string {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const num = parseInt(full, 16);
  let r = (num >> 16) + Math.round(255 * amt);
  let g = ((num >> 8) & 0xff) + Math.round(255 * amt);
  let b = (num & 0xff) + Math.round(255 * amt);
  r = Math.max(0, Math.min(255, r));
  g = Math.max(0, Math.min(255, g));
  b = Math.max(0, Math.min(255, b));
  return "#" + ((1 << 24) | (r << 16) | (g << 8) | b).toString(16).slice(1);
}
